sonar.projectKey=smartsched-uc
sonar.projectName=SmartSched-UC
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=sqp_eef59b88ec7ef1b6b6506eccb475f2883d5da7dd